name: "Release and deploy package to PyPI"

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  deploy:
    name: "Build and deploy to PyPI"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        poetry-version: ["1.8.3"]  # TODO: pass from env
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v5
      - name: "Setup Poetry ${{matrix.poetry-version}}"
        run: pipx install poetry==${{matrix.poetry-version}}
      - name: "Build package"
        run: poetry build
      - name: "Publish package"
        run: poetry publish --username=__token__ --password=${{secrets.PYPI_TOKEN}}
